<?php

/**
 * @file
 * Contains dd_csp_generator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dd_breakgen_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dd_csp_generator module.
    case 'help.page.dd_breakgen':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Automatic breakpoint to image style generator') . '</p>';
      return $output;

    default:
  }
}
